[supabase]
url = "https://ndplzodybdoupflduvgt.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kcGx6b2R5YmRvdXBmbGR1dmd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNTQwNzksImV4cCI6MjA3MTYzMDA3OX0.ym20q-43tvJmA_bqViAKzjXmEG7MI1JatRuwIVPBsqU"